theme: jekyll-theme-minimal


still thinking about it

this is an application to request and parse json data

so Can we take the json format and base bootstrap accordions off of the json levels??? YES

each top level gets a menu item

upon expanding a top level menu item the next level data displays

if any of those data children have children data they also get a +/- indicator and can be clicked to display their child data


right SO really really really = the JSON needs to be formated in a way to take advantage of the setup

let's make it DRY

very little code ... just loop through each level

+/- buttons can be applied to bar if the element has children

////////////////////////************************/////////////////////////////
REACT NATIVE APP - UI DEFINED BY JSON DATA

following the prescribed JSON data format React will build a consistent UI with collapsed multi-level menus of data

this mini App can be deploy to the web OR used as part of an iOS/Android app built with Reative Native